### ISSUE TITLE
Crossfade?

### ISSUE THREAD

**Issue by PrismBoy123** [iamMG/Song-Section-Skipper#1]
Is there any possible way to add crossfade between segments skipped?

It would make songs a **LOT** smoother with cleaner transitions 👍

Perhaps there’s a way to leverage the crossfade and automix in Spotify?

**Comment by iamMG** [comment]
I have a lot of things planned for this project, including Crossfade. However, I don't have time currently to focus on it. I will update this issue when I get to it.
